//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoggyStyle
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventExtention
    {
        public int EventExtentionId { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Ext_String_1 { get; set; }
        public string Ext_String_2 { get; set; }
        public Nullable<decimal> Ext_Numeric_1 { get; set; }
        public Nullable<System.DateTime> Ext_Date_1 { get; set; }
    }
}
