//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoggyStyle
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAllEvent
    {
        public int EventId { get; set; }
        public string EventSubject { get; set; }
        public string EventType { get; set; }
        public System.DateTime EventStartDate { get; set; }
        public Nullable<System.DateTime> EventEndDate { get; set; }
        public int EventDuration { get; set; }
    }
}
